In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [2]:
data = pd.read_csv('/content/house_prices.csv')

In [5]:
data.head()

   sqft_living  bedrooms  bathrooms  ...  dist_to_city_km  quality_score   price
0          959         4        2.0  ...            13.97              6  256153
1         3173         4        2.6  ...             1.40              4  602494
2         2017         1        1.9  ...             0.24              9  403973
3          818         5        3.7  ...            13.07              3  208514
4         2036         3        2.3  ...             1.90              5  396980

[5 rows x 8 columns]

In [7]:
data.shape

(1000, 8)

In [9]:
data.describe()

       sqft_living     bedrooms  ...  quality_score         price
count  1000.000000  1000.000000  ...    1000.000000  1.000000e+03
mean   1872.225000     3.368000  ...       6.581000  4.081768e+05
std     721.658094     1.189955  ...       2.240638  1.518990e+05
min     450.000000     1.000000  ...       3.000000  8.956100e+04
25%    1362.000000     3.000000  ...       5.000000  3.257180e+05
50%    1873.500000     3.000000  ...       7.000000  4.020970e+05
75%    2358.000000     4.000000  ...       9.000000  4.792382e+05
max    3927.000000     6.000000  ...      10.000000  2.558280e+06

[8 rows x 8 columns]

In [10]:
data.isnull().sum()

sqft_living         0
bedrooms            0
bathrooms          12
floors              0
house_age           0
dist_to_city_km     0
quality_score       0
price               0
dtype: int64

In [12]:
data['bathrooms']=data['bathrooms'].fillna(data['bathrooms'].median())
data.isnull().sum()

sqft_living        0
bedrooms           0
bathrooms          0
floors             0
house_age          0
dist_to_city_km    0
quality_score      0
price              0
dtype: int64

In [13]:
q1=data['price'].quantile(0.25)
q3=data['price'].quantile(0.75)
iqr=q3=q1
upper=q3+3*iqr
data=data[data['price']<upper]
data.shape

(997, 8)

In [14]:
X=data.drop(columns='price')
Y=data['price']
print(X)
print(Y)

     sqft_living  bedrooms  ...  dist_to_city_km  quality_score
0            959         4  ...            13.97              6
1           3173         4  ...             1.40              4
2           2017         1  ...             0.24              9
3            818         5  ...            13.07              3
4           2036         3  ...             1.90              5
..           ...       ...  ...              ...            ...
995         2530         2  ...             6.32              3
996         1159         3  ...             1.00              5
997         2530         3  ...             3.36              9
998          785         1  ...             0.77              5
999         3076         3  ...             5.67              6

[997 rows x 7 columns]
0      256153
1      602494
2      403973
3      208514
4      396980
        ...
995    442706
996    290977
997    512494
998    242206
999    574995
Name: price, Length: 997, dtype: int64

In [19]:
scaler=StandardScaler()

In [20]:
scaler.fit(X)
X_std=scaler.transform(X)
print(X_std)

[[-1.26516212  0.5313711  -0.55215823 ... -0.50272299  0.77894603
  -0.26273531]
 [ 1.80119768  0.5313711   0.07436122 ... -0.55543805 -0.86580809
  -1.15675274]
 [ 0.20015345 -1.99137647 -0.65657814 ...  2.71289585 -1.01759129
   1.07829083]
 ...
 [ 0.91065145 -0.30954475 -0.44773833 ...  0.92058371 -0.60934683
   1.07829083]
 [-1.50614974 -1.99137647 -1.59635732 ... -0.81901336 -0.94824207
  -0.70974402]
 [ 1.666854   -0.30954475 -0.34331842 ... -0.02828742 -0.30708891
  -0.26273531]]

In [22]:
X=X_std

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)
print(X.shape,X_train.shape,X_test.shape)

(997, 7) (797, 7) (200, 7)

In [24]:
cf2=RandomForestRegressor(n_estimators=200,max_depth=10,random_state=2)
cf2.fit(X_train,Y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=2)

In [25]:
X_train_pred=cf2.predict(X_train)
train_score=r2_score(Y_train,X_train_pred)
print(train_score)

0.9914272926864008

In [26]:
X_test_pred=cf2.predict(X_test)
test_score=r2_score(Y_test,X_test_pred)
print(test_score)

0.9438451796541517

In [27]:
data2=[2150,3,2.0,8,5,4,7]
print(data2)

[2150, 3, 2.0, 8, 5, 4, 7]

In [28]:
data_np=np.asarray(data2)
print(data_np)

[2.15e+03 3.00e+00 2.00e+00 8.00e+00 5.00e+00 4.00e+00 7.00e+00]

In [30]:
data_reshape=data_np.reshape(1,-1)
print(data_reshape)

[[2.15e+03 3.00e+00 2.00e+00 8.00e+00 5.00e+00 4.00e+00 7.00e+00]]

In [31]:
input_std=scaler.transform(data_reshape)
print(input_std)

[[ 0.38435664 -0.30954475 -0.55215823 10.41275705 -0.7662983  -0.52560437
   0.1842734 ]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [32]:
pred=cf2.predict(input_std)
print(pred)

[460258.67371491]