In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
data=pd.read_csv('/content/diabetes.csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,4,143.7,77.7,0.0,45.9,38.1,0.370,46,0
1,4,195.5,67.6,0.0,0.0,37.6,0.080,66,1
2,5,108.7,33.2,0.0,0.0,46.3,0.439,23,1
3,1,106.5,76.1,22.2,22.3,26.6,0.080,24,0
4,7,123.8,33.8,6.9,109.5,33.7,0.197,21,1

In [5]:
data.shape

(768, 9)

In [6]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.010417,120.510807,65.679427,14.172656,52.170182,31.775000,0.458740,33.102865,0.342448
std,1.721070,31.205064,22.436778,15.280252,75.771389,8.891549,0.425776,13.561145,0.474838
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080000,21.000000,0.000000
25%,2.000000,99.175000,54.075000,0.000000,0.000000,26.900000,0.142750,21.000000,0.000000
50%,3.000000,121.350000,67.350000,9.950000,22.050000,31.500000,0.313000,29.000000,0.000000
75%,4.000000,142.025000,79.300000,25.225000,73.275000,37.800000,0.647500,40.000000,1.000000
max,9.000000,199.000000,122.000000,71.900000,563.600000,56.500000,2.420000,81.000000,1.000000

In [7]:
data['Outcome'].value_counts()

Outcome
0    505
1    263
Name: count, dtype: int64

In [8]:
data.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,2.908911,114.982772,65.699802,13.131683,51.513069,31.299406,0.439608,31.651485
1,3.205323,131.125475,65.640304,16.171483,53.431939,32.688213,0.495475,35.889734

In [9]:
x=data.drop(columns='Outcome',axis=1)
y=data['Outcome']

In [10]:
print(x)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              4    143.7           77.7            0.0     45.9  38.1
1              4    195.5           67.6            0.0      0.0  37.6
2              5    108.7           33.2            0.0      0.0  46.3
3              1    106.5           76.1           22.2     22.3  26.6
4              7    123.8           33.8            6.9    109.5  33.7
..           ...      ...            ...            ...      ...   ...
763            2    133.5           89.1           41.6    102.1  42.1
764            3    137.5           74.2           31.4      0.0  41.7
765            2    154.9           33.8            4.3      0.0  46.9
766            2     90.0           50.6            3.5     40.0  31.9
767            8     91.0           79.7            0.0     15.5  21.8

     DiabetesPedigreeFunction  Age
0                       0.370   46
1                       0.080   66
2                       0.439   23
3                       0.080   24
4                       0.197   21
..                        ...  ...
763                     0.213   33
764                     0.829   26
765                     0.567   36
766                     0.479   32
767                     0.586   63

[768 rows x 8 columns]

In [11]:
print(y)

0      0
1      1
2      1
3      0
4      1
      ..
763    0
764    0
765    1
766    1
767    1
Name: Outcome, Length: 768, dtype: int64

In [12]:
scaler=StandardScaler()

In [13]:
scaler.fit(x)
x_std=scaler.transform(x)

In [14]:
print(x_std)

[[ 0.57535618  0.74360702  0.53610221 ...  0.71181323 -0.20855445
   0.95165563]
 [ 0.57535618  2.40467579  0.0856551  ...  0.65554341 -0.89010813
   2.42741843]
 [ 1.15676874 -0.37873674 -1.448541   ...  1.63463829 -0.04639168
  -0.74547158]
 ...
 [-0.58746894  1.10275703 -1.42178177 ...  1.70216207  0.25443202
   0.21377423]
 [-0.58746894 -0.97838898 -0.67252321 ...  0.01406746  0.04761573
  -0.08137833]
 [ 2.90100643 -0.94632201  0.62529966 ... -1.12258292  0.29908554
   2.20605401]]

In [15]:
x=x_std

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [17]:
print(x.shape,x_train.shape,x_test.shape)

(768, 8) (614, 8) (154, 8)

In [18]:
cf = svm.SVC(kernel='linear')

In [19]:
cf.fit(x_train,y_train)

SVC(kernel='linear')

In [20]:
x_train_pred=cf.predict(x_train)

In [21]:
x_train_acc=accuracy_score(x_train_pred,y_train)

In [22]:
print(x_train_acc)

0.6954397394136808

In [23]:
x_test_pred=cf.predict(x_test)
x_test_acc=accuracy_score(x_test_pred,y_test)
print(x_test_acc)

0.7077922077922078

In [24]:
sample_input = [[
    4,      # Pregnancies
    143.7,  # Glucose
    77.7,   # BloodPressure
    0.0,    # SkinThickness
    45.9,   # Insulin
    38.1,   # BMI
    0.37,   # DiabetesPedigreeFunction
    46      # Age
]]

In [26]:
sample_input = scaler.transform(sample_input)

prediction = cf.predict(sample_input)

print(prediction)

[0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(